# Syllabus {#AppA}

|Lesson Topic                           | Reading       | Homework  |
|-------------------------------------|:----------------------------------------:| -----------------------------------:|
| [Admin and Course Introduction](#L1)     | Page xv-xviii, A.1, A.2, A.4 up to A.4.1 |  |
| [Summarizing Univariate Data](#Les2)           | 1.1 - 1.2                                |1.2, 1.4, 1.6, 1.8, 1.10, 1.13 |
| [Summarizing Multivariate Data](#L3)         | 1.3 - 1.4                                |1.15, 1.16, 1.17, 1.19, 1.21, 1.25 |
| [Random Variables](#L4)	                      | 2.1, B.1 - B.3                           |2.1, 2.2, B.1, B.2, B.3, B.4, B.6, B.19|
| [Probability Rules]($L5)	| 2.2-2.2.6	| 2.6, 2.7, 2.9, 2.10, 2.11, 2.29 |
| [Inclusion-Exclusion, Conditional Probability](#L6)|	2.2.7	|2.14, 2.15, 2.18, 2.21, 2.24, 2.25 |
| [Discrete Distributions](#L7) |	2.3	|2.30, 2.40, 2.43, 2.44, 2.45, 2.46|
| [Intro to Hypothesis Testing](#L8) |	2.4	|2.51, 2.52, 2.53, 2.55, 2.56|
| [Mean and Variance of Discrete Random Variable](#L9) |	2.5	|2.60, 2.61, 2.64, 2.65, 2.67 |
| [Discrete Joint Distributions](#L10) |2.6	|2.71, 2.76, 2.92, 2.95|
| [Other Discrete Distributions](#L11) |	2.7 thru 2.7.3|	2.80, 2.81, 2.85, 2.86, 2.88|
| [Uniform and Exponential Distribution](#L12) |	3.1	|3.1, 3.3 3.5, 3.7|
| [Moments](#L13) |	3.2 thru 3.3 Stop at 3.3.1 | 	3.8, 3.10, 3.12|
| [Generating Functions](#L14)	|3.3.1 - 3.3.4	 |3.14, 3.19, 3.30a|
| [Important Continuous Distributions](#L15)	|3.4	|3.29, 3.31, 3.32, 3.33, 3.34|
| [Plots of Distributions](#L16)	|3.5-3.6	|3.38, 3.39, 3.40, 3.41|
| [Continuous Joint Distributions](#L17)	|3.7	|3.44, 3.45, 3.47, 3.50, 3.51|
| [Method of Moments](#L18)	|4.1-4.2	|4.1, 4.2, 4.3, 4.5, 4.7, 4.9|
| [Estimates and Estimators](#L19)	|4.3	|4.11, 4.13, 4.15, 4.16|
| [Limit Theorems](#L20)	|4.4	|4.14, 4.19, 4.20, 4.21|
| [Inference for Mean (Variance Known)](#L21)	|4.5	|4.22, 4.25, 4.26, 4.27, 4.28|
| [Estimating Variance](#L22)	|4. 6 - 4.7	|4.30, 4.39, 4.41, 4.42, 4.44|
| [Two Additional Tests](#L23) |	4.8-4.9	|4.50, 4.51, 4.52|
| [Permutations Tests](#L24) |	4.10	|4.53, 4.54, 4.56, 4.57|
| [Maximum Likelihood Estimators](#L25) |	5.1	|5.1, 5.2, 5.9,5.12|
| [Likelihood Ratio Tests](#LRT) |	5.2	|5.17, 5.18, 5.22|
| [Goodness of fit](#L27) |	5.4	|5.19, 5.20, 5.21|
| [Two-Way Tables](#L28)	|5.5	|5.23(not f), 5.27, 5.28|
| [Introduction to Linear Models](#L29)	|6.1, C.2| Problem given in Notes |
| [Simple Linear Regression](#L30) |	6.2	|6.2, 6.4, 6.5, 6.6|
| [Inference for Simple Linear Regression](#L31)	|6.3	|6.7, 6.8, 6.25, 6.26|
| [Diagnostics](#L32)	|6.4	|6.27, 6.28, 6.29, 6.32 (not part b)|



